# get list of sub-directories
macro(PROTEAN3D_SUBDIRLIST result srcdir)
  file(GLOB children RELATIVE ${srcdir} ${srcdir}/*)
  set(dirlist "")
  foreach(child ${children})
    if(IS_DIRECTORY ${srcdir}/${child})
        SET(dirlist ${dirlist} ${child})
    endif()
  endforeach()
  set(${result} ${dirlist})
endmacro()

macro(PROTEAN3D_WRITE_GL_CONFIGURATION headerlist)
  SET(PROTEAN3D_GL_CONFIG_FILE ${PROJECT_BINARY_DIR}/generated_headers/gl_includes.h)
  file(WRITE ${PROTEAN3D_GL_CONFIG_FILE}  "// GENERATED FILE - DON'T TOUCH!\n" )
  file(APPEND ${PROTEAN3D_GL_CONFIG_FILE} "#pragma once\n\n" )
  foreach(header ${headerlist})
    file(APPEND ${PROTEAN3D_GL_CONFIG_FILE}  "#include <${header}>\n" )
  endforeach()
endmacro()
